#cloud-config
apt_update: true
package_upgrade: true
packages:
  # common
  - make
  # redis
  - gcc
  - libc6-dev
  - curl
runcmd:
  - echo 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' > /etc/rc.local
  - sysctl vm.overcommit_memory=1
  - echo 1024 > /proc/sys/net/core/somaxconn
  # ufw
  - ufw default deny incoming
  - ufw default allow outgoing
  - ufw allow 22/tcp
  - ufw allow 6379/tcp
  - ufw enable
  # redis
  - curl -sSL http://download.redis.io/releases/redis-stable.tar.gz -o /tmp/redis.tar.gz
  - mkdir -p /tmp/redis
  - tar -xzf /tmp/redis.tar.gz -C /tmp/redis --strip-components=1
  - make -C /tmp/redis
  - make -C /tmp/redis install
  - echo -n | /tmp/redis/utils/install_server.sh
  - rm -rf /tmp/redis*
  - cp /tmp/redis_config.conf /etc/redis/6379.conf
  - rm -rf /tmp/redis_config.conf
  - service redis_6379 restart
power_state:
  mode: reboot
  timeout: 30
